+++
date = "2016-02-13T10:03:59+01:00"
subtitle = ""
title = "Biche"
photo = "photos/biche.jpg"
tags = ["cervidé","mammifère"]
categories = ["mammifère"]
+++

=== Seule un matin

Un matin, j'ouvre les volets. Je me rends compte qu'au fond du jardin juste derrière le ruisseau, des feuilles bougent. je regarde plus attentivement, et je vois une masse marron fauve. Puis tout d'un coup, une tête se lève. C'est une biche. Quand on la voit de face, il n'y a aucun doute. Elle nous observe aussi. Et on reste planté là, à s'observer.

Je finis par partir car je travaille et il faut bien que je me prépare. Et puis au bout d'un moment, je reviens quand même voir à la fenêtre et je me rends compte qu'elle est toujours là mais de profil cette fois. Elle mange les feuilles des jeunes pousses.

Puis elle a finit par partir, mais je ne sais pas par où car je ne l'ai pas vu.

=== A deux, en journée

Un jour que Max était là, je vais à la fenêtre de notre chambre, je dis aux garçons de sortir et on se rend compte que 2 biches mangent les plantes à la lisière du ruisseau

Quand nous avons approché, les deux biches sont partis en courant et bondissant au dessus des grillages des différents terrains en direction de la forêt.
