+++
categories = [""]
date = "2016-02-13T12:41:46+01:00"
photo = "photos/chevreuil.jpg"
subtitle = ""
tags = ["", ""]
title = "Chevreuil"

+++

=== Au fond du jardin

Comme je le fais souvent, quand je rentre du boulot, je fais un tour du jardin. Des framboises sont présentes, je rentre à la maison et je reviens avec un bol pour en ramasser.

Je repasse derrière la haie, et puis je me mets à ramasser mes framboises footnote:[Mon framboisier se situe sur le terrain mais à la limite du ruisseau]. Puis tout d'un coup, j'entends qu'on frappe derrière moi. Je me retourne, je ne vois rien, donc je continue. Puis voilà, que ça refrappe derrière moi.

Je me retourne mais cette fois ci, je ne suis plus seule, un magnifique chevreuil tape le sol avec ses sabots de l'autre coté du ruisseau. Je ne suis pas tranquille, je l'observe, lui aussi visiblement et puis je retourne à mes occupations.

Une fois fini, je repars vers la cuisine, à la limite de la haie, je me retourne, il est toujours là et me regarde partir.

Je suis assez impressionnée, car je n'ai pas eu peur plus que ça de lui, lui n'a pas fuit en me voyant si près de lui (environ 3m pas plus).
