+++
categories = ["oiseau"]
date = "2016-02-13T12:43:04+01:00"
photo = "photos/epervier.jpg"
subtitle = ""
tags = ["oiseau", "rapace"]
title = "Epervier"

+++

=== Dans le nid au fond du jardin

Sam a vu l'épervier se poser sur les arbres au fond du jardin, dans l'ancien nid de corbeau. Il était magnifique, majestueux. On a pu l'observer que quelques minutes. Il est reparti en déployant ces grandes ailes.
Quel oiseau !

=== Sur les piquets.

Le long de la D3, entre le village et la forêt, il y en a toujours un sur un piquet. Il ne bouge pas, il observe. On le voit principalement, le soir à la nuit tombante.

=== Dans la forêt

Souvent le matin, on peut le voir dans le champ au milieu de la forêt. Il traque les rongeurs. Il me fait toujours pensé à un gros poulet !

je lui ai donné un petit nom : poitrail blanc.

=== Dans le jardin

Depuis que Enedis a coupé les arbres à la lisière de notre jardin, on aperçoit de temps en temps un épervier soit dans notre pommier, soit dans notre cerisier. Il reste là, pendant une heure dès fois, à regarder les oiseaux dans notre jardin. Puis au bout d'un moment, il décole et s'envole en longeant le ruisseau. Il est impressionnant. 
