+++
categories = ["mammifère"]
date = "2016-02-13T12:50:07+01:00"
photo = "photos/renard.jpg"
subtitle = ""
tags = ["mammifère"]
title = "Renard"

+++

=== Prés du ruisseau

Nous avons derrière le jardin, un espèce de bosquet. Un jour, dans l'après midi, on voit en bas de ce bosquet quelque-chose de roux fauve qui passe et là, dans le trou du bosquet, je vois un beau renard. Heureusement, nous n'avons pas de poule, ce qui n'est pas le cas des gens de l'autre coté du champs.

Il a passé son chemin comme ça, sans rien dire, mais vraiment très près de chez nous.

=== Vers Gomelange

Je prends la route pour aller à la poste, et puis au milieu de la route, je vois un renard. Je ralentis pour le laisser passer. Mais celui-ci reste au milieu et me regarde. Je m'arrête. Il attend. Au bout de 5 minutes, le renard repart et va dans le champ. Et puis, je suis repartie

=== Dans le champs

Tous les matins, ces derniers temps, on voit un renard, et puis ce matin, on a vu le renard plonger dans son terrier. Ce qui est marrant, c'est que ce terrier se situe en plein milieu d'un champ où sont en permanance des vaches. En même temps les vaches n'ont pas l'air perturbé par la présence de ce renard en permanence.

=== En revenant de nuit

Je voyais deux billes qui reflétait dans les phares de la voiture sur le coté de la route.  Une fois qu'il était plus près, j'ai pu voir un beau renard longer la route.
