+++
categories = ["mammifère"]
date = "2016-02-13T12:51:08+01:00"
photo = "photos/sanglier.jpg"
subtitle = ""
tags = ["mammifère", "porc"]
title = "Sanglier"

+++

=== Un soir dans la forêt

Ce soir, je suis rentrée du sport en voiture. Comme nous sommes en hiver, il fait nuit quand je rentre. Je roule dans la forêt, je suis seule donc en plein phare. je roule et au loin, j'aperçois une grosse masse en limite de chaussée. Plus j'avance et plus je trouve que cette masse est vraiment importante. Je ralentis quand je suis en approche et là, tout d'un coup, la masse tourne la tête. Elle a des défenses, c'est un énorme sanglier. Ses yeux sont à hauteur de pare-brise. Là, j'ai eu vraiment peur. Comme je ne sais pas quoi faire dans ses cas là, je n'ai rien fait à part freiner un peu plus.
Je pense qu'à un moment, il en a eu marre d'avoir mes phares dans la tête, du coup il est reparti dans la forêt.

500 m plus loin, je me rends compte qu'à la limite de la forêt, un marcassin était présent.

Quelle soirée !

=== A l'entrée du village

Encore une fois, un soir en rentrant du sport, à la sortie de la foret et avant de rentrer dans le village, j'ai rencontré 4 sangliers sur le bord de la route. J'avoue que je n'étais pas tranquille.
