+++
categories = ["oiseau"]
date = "2016-02-13T12:53:05+01:00"
photo = "photos/bergeronnettegrise.jpg"
subtitle = ""
tags = ["oiseau","occasionnel"]
title = "Bergeronnette grise"

+++

=== Première fois

C'est la première année que j'en vois. Je trouve cet oiseau très beau, noir, blanc et gris. J'en avais une en train de manger des insectes contenus dans la mousse présente sur la terrasse à cause de la pluie abondante en ce printemps.

Je l'ai vu 2 jours de suite, mais je ne l'ai pas revu depuis.

=== Suite

Finalement, elle a fini par revenir, elle est partie de la terrasse à pied et à fait le tour du jardin. Elle est passée très près de moi en dessous de la fenêtre de la chambre. Je pense qu'elle cherchait des insectes.
Puis elle est repartie.

=== Sur le toit

Je faisais le tour du jardin, et en levant la tête, je me suis aperçue que la bergeronnette était sur le fet du toit.
Elle regardait partout à la recherche d'insectes peut être. Il faut dire qu'avec les saules qui perdent leurs graines, ça vole partout.
