+++
categories = ["oiseau"]
date = "2016-03-19T09:47:58+01:00"
photo = "photos/geaideschenes.png"
subtitle = ""
tags = ["oiseau", "geai","occasionnel"]
title = "Geai Des Chênes"

+++

=== Au pied du pommier

Ce matin, ce bel oiseau était dans mon jardin en train de chercher des insectes. Il est resté un bon moment. Nous en avons aperçu un deuxième pas très loin. Comme nous sommes fin mars, je soupçonne que ce soit un couple car nous sommes en période de reproduction pour plein d'oiseaux.

Il faut dire que c'est un oiseau imposant car de bonne taille. Je n'avais jamais vu cet oiseau de si près.

=== Dans le cerisier

J'ai vu un épervier dans mon cerisier, peu de temps après son arrivé, un geai s'est aussi poser sur ce même cerisier. On avait l'impression qu'il chasser ensemble pour manger. Un respect entre les deux oiseaux semblait s'être instauré. Pour autant, il y avait une ambiance particulière dans le jardin.

=== Un couple

Ce matin, j'ai aperçu un geai dans le pommier, au même moment, un deuxième geai était présent dans le cerisier. On a l'impression que c'est un couple. Ils sont repartis par le ruisseau ensemble. 
