+++
categories = ["oiseau"]
date = "2016-02-21T10:26:56+01:00"
photo = "photos/mesangen.jpg"
subtitle = ""
tags = ["oiseau", "mésange","occasionnel"]
title = "Mésange nonnette"
+++

=== Dans le distributeur de graines

C'est vraiment la première fois que je vois ce type de mésange, un "poil" plus petite que les mésanges à tête bleue ou les mésanges charbonnières. Moins de couleur aussi.
Ce matin, c'était un couple que se relayait. Quand une était dans les graines, la deuxième était sur la branche en dessous, puis au bout de quelques secondes, elles échangaient leur place.

Les mésanges nonettes sont revenues dans la mangeoire à oiseau, elles se rapprochent et n'ont presque plus peur de moi. Je pense qu'elles ont vu que c'est moi qui met les graines ! (enfin j'interprète)

=== Dans la haie

Ce matin en me levant, j'ai ouvert les volets. J'avais mis deux ramequins de graines pour les oiseaux dehors sur la terrasse près de la haie. En regardant la haie vers l'un des ramequins,  j'ai aperçu 2 mésanges nonettes. Ce n'est pas souvent qu'on les aperçoit.
