+++
categories = ["reptile"]
date = "2016-02-13T14:02:33+01:00"
photo = "photos/orvet.jpg"
subtitle = ""
tags = ["reptile", "serpent"]
title = "Orvet"

+++

=== Sous la terrasse.

Ce fût un passage furtif que nous avons observé au coin de la terrasse, un petit serpent bronze. Il se dorait au soleil. Quand il nous a apperçu, il s'est glissé sous la terrasse (entre la dalle de béton et les lattes de bois).

=== Prés du ruisseau.

C'est un nid qu'on à la bas. 2 orvets qui me sont passés entre les jambes. Ca fait tout bizarre de les voir se glisser.

=== Dans la descente de garage

Il a eu de la chance, on ne lui a pas roulé dessus avec la voiture. Il se déplace comme un serpent mais visiblement, ça n'en ait pas un. Il a plutot une tete de lézard. Il est couleur bronze. Il attire l'oeil car très joli. Il est allé se glisser entre les pierres.

=== Devant le lave linge

Je suis descendu au garage pour lancer une lessive. Je veux poser mon panier de linge au sol, et là je vois un orvet qui attendait. J'ai du aller chercher du renfort pour le dégager de là ! Nous l'avons glissé sous une feuille et mis devant le garage. Je pense qu'il cherchait la chaleur.
