+++
categories = [""]
date = "2016-02-13T14:06:43+01:00"
photo = "photos/picvert.jpg"
subtitle = ""
tags = ["", ""]
title = "Pic vert"

+++

=== Dans la neige

Un matin où les parents été présents, nous avons ouvert les volets du coté du salon et en observant, nous avons vu dans la neige, un pic vert en train de creuser des trous. Ils cherchent des vers ou les graines des plantes. Il est resté bien 1h30 à creuser sur le devant de la maison.

Nous avons eu le temps de l'observer, c'est un oiseau dodu et très grand, facilement de la taille d'une petite caille.

=== Près du ruisseau

Nous l'avons revu souvent au pied du cerisier en train de fouiller la terre. Il faut dire que le cerisier est souvent recouvert de fourmis. Même si on fait des fois du bruit, il ne s'envole pas mais reste à distance.

=== En couple

Ce soir, je vois un pic-vert décoller du jardin vers les arbres près du ruisseau. Puis je regarde au sol, et là je vois un deuxième pic vert. Les deux sont de la même couleur mais c'est quand même peut-être un couple. Ils étaient visiblement en train de dévorer les fourmis au niveau des fourmillères.

=== Un matin d'hiver

Ce matin, j'ai ouvert les volets, le pic vert était dans le jardin. Il a entendu le bruit du volet, il s'est envolé dans le cerisier. Il a passé 10 minutes à picorer le tronc. Puis s'est envolé au sol pour manger les fourmis.
