+++
categories = ["oiseau"]
date = "2016-03-26T13:46:05+01:00"
photo = "photos/pinson.jpg"
subtitle = ""
tags = ["oiseau"]
title = "Pinson des arbres"

+++

=== Première fois

Ce n'est pas moi que l'est vu, mais Sam. Il l'a pris en photo, celui ci était dans un arbre, puis s'est envolé.

=== Dans la mangeoire

Cette fois ci, c'est la femelle que nous avons vu, elle est beaucoup moins colorée que son conjoint mais joli quand même. Elle aussi, elle apprécie les graines qu'on met dans le jardin.

=== Sur un arbre

Le lendemain, c'est le male qui était dans l'arbre au fond du jardin. Il est resté là sur une branche presque une heure. Je suis sortie le prendre en photo. Je me suis même approchée, et il ne s'est pas envolé. Par contre, il avait gonflé les plumes, ce qui fait que j'ai eu du mal à le reconnaitre.

=== A Metz

Comme tous les midis, je me balade le long de la Moselle pour profiter d'un moment nature et faire une pause au boulot. Ce midi, en me baladant j'ai vu un couple de pinson dans le parc de la Cavalerie. Il faut dire que c'est un bel oiseau avec ses couleurs.
Et en revenant au boulot, il y en avait un dans un arbuste près d'un de nos batiments administratif.
