+++
categories = [""]
date = "2016-02-13T14:12:39+01:00"
photo = "photos/rougequeue.jpg"
subtitle = ""
tags = ["", ""]
title = "Rouge-queue"

+++

=== Observation

C'est un oiseaux qui n'est pas très farouche car il est souvent sur la terrasse. Souvent seul, il aime se poser sur les tuteurs ou sur les bambous qui servent de décoration. Il observe pendant de longues minutes, puis il plonge au sol pour manger.

=== Printemps frais

En rentrant du boulot, j'ouvre les volets de la pièce principale, et je vois un rouge-queue dans le jardin, plutôt proche de la maison.
Je me dis qu'il va s'envoler car je fais beaucoup de bruit, mais non, il reste là. Et puis, le voilà qui sautille dans l'herbe pour trouver des insectes.
Puis il repart en s'envolant.

=== Sur la fenêtre

Je vais dans la chambre pour récupérer mon sac, je regarde les chats dormir, je tourne la tête par la fenêtre et que vois-je sur le rebord, le rouge-queue !
C'est la première fois que j'ai pu voir d'aussi près son ramage. Dégradé de marron sur les plumes, puis rouge sur la queue.
Quand il a décollé (sentant ma présence), j'ai pu voir que les plumes sous celles des ailes, sont bien rouges.
Et comme à son habitude, il est parti se poser sur le tuteur de l'érable.

=== Peut-être un petit

Je vois le rouge-queue se poser sur le fil à linge. Je l'observe, il a quelque-chose dans son bec, mais j'avoue, je n'ai pas eu le temps de voir quoi. puis il part dans notre haie de laurier d'ornement.
Je le revois quelques secondes après sur le tuteur du ginkgo puis il se pose au sol, attrape un truc et repart dans la haie.

Peut-être, aurait-il son nid dans la haie ?

Aprés quelques jours d'observation, je me rends compte qu'il part toujours de la haie. Du coup, je lui ai mis des miettes de pain au pied de la haie pour qu'il aie un peu à manger l'hiver
