+++
categories = ["oiseau"]
date = "2016-02-13T14:21:17+01:00"
photo = "photos/troglodytemignon.jpg"
subtitle = ""
tags = ["oiseau", "courant"]
title = "Troglodyte mignon"

+++

=== Sous la haie

Ce soir en rentrant, je remarque un truc qui bouge sous la haie de troën. J'observe et là je vois un tout petit oiseau qui gazouille gaiement. C'est un cri que je reconnais car ça fait plusieurs jours que je l'entends et que je me demandais d'où il pouvait venir.

=== Sur la terrasse

Je regarde par la fenêtre et je vois un tout petit oiseau. 5 à 8 cm pas plus. Peut-être même moins. Je le vois sautiller puis aller dans la haie le long de la terrasse. Peu de temps après, je l'ai vu voler de la haie de laurier à la haie le long du jardin. Visiblement, c'est un oiseau qui aime bien les arbustes en haie.

En y réfléchissant, quand nous avons emmenagé, nous avons vu souvent cet oiseau dans la haie le long du ruisseau mais jamais nous ne l'avions vu d'assez pret pour savoir quel oiseau c'était.

=== Dans le pot de fleur

En regardant le pot de fleurs qui fait angle entre la maison et la terrasse, je revois le troglodyte. il nous regarde à travers la fenêtre mais ne part pas. Il piaille beaucoup d'un cri très aigu. En tout cas, il n'est pas très farouche et il est vraiment petit.

=== Sur le grillage du voisin

Ca faisait un moment que nous n'en avions pas vu. Mais il y en avait un, sur le grillage du voisin. Facilement reconnaissable grace à son chant et à sa taille. Ca fait plaisir d'en revoir.
